trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: 
    cd platform
    composer install --no-interaction --prefer-dist
  displayName: 'composer install'
- script: |
    cd platform
    cp .env.example .env
    php artisan key:generate
  displayName: 'Set up Laravel environment'

- script: |
    cd platform
    php artisan test
  displayName: 'Run Laravel Tests'
