name: Go

on:
  push:
    branches: [ "main", "go-cli" ]
  pull_request:
    branches: [ "main", "go-cli" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd service
        go build -v -o pgc main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pgc
        path: service/pgc

  test:
    runs-on: ubuntu-latest
    # needs: build  # This ensures the test job runs after the build job
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    # - name: Download build artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: myapp-binary

    - name: Test
      run: |
        cd service
        go test -v ./...
