name: Build and Package Go Project

on:
  release:
    types: [created]
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Go project
        run: |
          cd service
          go build -v -o pgc main.go

      - name: Install FPM and YAML tools
        run: |
          sudo apt-get install -y ruby ruby-dev gcc make rpm-build
          sudo gem install --no-document fpm
          sudo apt-get install -y yq  # For parsing YAML

      - name: Build .deb and .rpm packages
        run: |
          cd service
          bash ./build_package.sh

      - name: Upload .deb and .rpm to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./service/*.deb
          asset_name: plataforma-gestion-contenedores${{ github.ref_name }}.deb
          asset_content_type: application/octet-stream

      - name: Upload RPM
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./service/*.rpm
          asset_name: plataforma-gestion-contenedores${{ github.ref_name }}.rpm
          asset_content_type: application/octet-stream
